name: Client deployment workflow

on:
  release:
    types: [published]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setting up enviroment
        uses: actions/checkout@v2
      - name: listing files
        run: ls -R
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: install dependencies
        run: cd ./client && yarn install
      - name: build client package
        run: cd ./client && yarn build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: client-dist
          path: ./client/dist
  deploy: 
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Dowload dist artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: client-dist
          path: .
      - name: Display structure of downloaded files
        run: ls -R
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
          
            
