# This is a basic workflow to help you get started with Actions
name: Client deployment workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setting up enviroment
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: install dependencies
      - run: cd ./client
      - run: yarn install
      - name: build client package
      - run: yarn build
      - name: Upload dist artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: client-dist
          path: ./client/dist
  deploy: 
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Dowload dist artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: client-dist
      - name: Deploy to GitHub Pages
      - id: deployment
      - uses: actions/deploy-pages@v1
       
          
            
