# This is a basic workflow to help you get started with Actions

name: server-build-create-image-publish

on:
  release:
    types: [published]
    
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: install dependencies
        run: cd ./server && yarn install
      - name: build server package
        run: cd ./server && yarn build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:server"
          push: true
          tags: user/app:latest
